#ifndef HIBABL_CORE_MEMORY_H
#define HIBABL_CORE_MEMORY_H


/* This is protected mode stack*/
#define HIBABL_MEMORY_MACHINE_PM_STACK 0x7FFF0
/* This is real mode stack. */
#define HIBABL_MEMORY_MACHINE_REAL_STACK 0x2000 - 0x10

/* These are the segment selectors offset in our gdt. */
#define HIBABL_MEMORY_MACHINE_PM_CS 0x8
#define HIBABL_MEMORY_MACHINE_PM_DS 0x10
#define HIBABL_MEMORY_MACHINE_RM_CS 0x18
#define HIBABL_MEMORY_MACHINE_RM_DS 0x20

/* This is the information related to the E820 memory map. */
#define HIBABL_MEMORY_MACHINE_E820_ADDR 0x2000
#define HIBABL_MEMORY_MACHINE_E820_MAX 128
#define HIBABL_MEMORY_MACHINE_E820_ENTRY_SIZE 20
#define HIBABL_MEMORY_MACHINE_E820_TOTAL_SIZE HIBABL_MEMORY_MACHINE_E820_MAX*HIBABL_MEMORY_MACHINE_E820_ENTRY_SIZE
#define HIBABL_MEMORY_MACHINE_E820_END_ADDR HIBABL_MEMORY_MACHINE_E820_ADDR+HIBABL_MEMORY_MACHINE_E820_TOTAL_SIZE

/* This is the info related to pmm. */
#define HIBABL_MEMORY_MAX_DYNAMIC_MB 128
#define HIBABL_MEMORY_DYNAMIC_COVERAGE HIBABL_MEMORY_MAX_DYNAMIC_MB*0x100000
#define HIBABL_MEMORY_BITMAP_SIZE HIBABL_MEMORY_MAX_DYNAMIC_MB*32
#define HIBABL_MEMORY_PAGE_SIZE 4096

/* This is info related to our heap. */
#define HIBABL_MEMORY_HEAP_INITIAL_SIZE 1024*1024*4
#define HIBABL_MEMORY_HEAP_GROWTH_RATE 1024*1024

/* The second bit is the one we have to toggle for protected mode */
#define HIBABL_MEMORY_CPU_CR0_PE_ON 1

#endif