#ifndef HIBABL_CORE_OFFSET_H
#define HIBABL_CORE_OFFSET_H

#define HIBABL_MACHINE_STAGE1_ADDR 0x7C00

#define HIBABL_MACHINE_PARTITION_TABLE_ADDR 0x1BE + HIBABL_MACHINE_STAGE1_ADDR
#define HIBABL_MACHINE_PARTITION_ENTRY_SIZE 0x10
#define HIBABL_MACHINE_PARTITION_ENTRY_COUNT 4

#define HIBABL_MACHINE_SCRATCH_ADDR 0x7E00

#define HIBABL_MACHINE_STAGE2_ADDR 0x8000

#endif